FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ./IntegrationTests/ ./IntegrationTests/
WORKDIR /src/IntegrationTests

RUN dotnet restore
RUN dotnet build --configuration Release
CMD ["dotnet", "test", "--configuration", "Release", "--no-build", "--logger:trx"]
