FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

COPY proto ./proto

COPY RuleEngine/ ./src/

WORKDIR /app/src
RUN dotnet restore
RUN dotnet publish -c Release -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /publish .
ENTRYPOINT ["dotnet", "RuleEngine.dll"]