version: "3.9"

services:

  configsvr1:
    image: mongo:6.0
    container_name: configsvr1
    command: mongod --configsvr --replSet configReplSet --port 27019 --bind_ip_all
    ports:
      - 27019:27019
    volumes:
      - configsvr1_data:/data/db
    networks:
      - app_network

  configsvr2:
    image: mongo:6.0
    container_name: configsvr2
    command: mongod --configsvr --replSet configReplSet --port 27019 --bind_ip_all
    volumes:
      - configsvr2_data:/data/db
    networks:
      - app_network

  configsvr3:
    image: mongo:6.0
    container_name: configsvr3
    command: mongod --configsvr --replSet configReplSet --port 27019 --bind_ip_all
    volumes:
      - configsvr3_data:/data/db
    networks:
      - app_network

  # Shard 1 replica set
  shard1_1:
    image: mongo:6.0
    container_name: shard1_1
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018 --bind_ip_all
    volumes:
      - shard1_1_data:/data/db
    networks:
      - app_network

  shard1_2:
    image: mongo:6.0
    container_name: shard1_2
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018 --bind_ip_all
    volumes:
      - shard1_2_data:/data/db
    networks:
      - app_network

  shard1_3:
    image: mongo:6.0
    container_name: shard1_3
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018 --bind_ip_all
    volumes:
      - shard1_3_data:/data/db
    networks:
      - app_network

  # Shard 2 replica set
  shard2_1:
    image: mongo:6.0
    container_name: shard2_1
    command: mongod --shardsvr --replSet shard2ReplSet --port 27018 --bind_ip_all
    volumes:
      - shard2_1_data:/data/db
    networks:
      - app_network

  shard2_2:
    image: mongo:6.0
    container_name: shard2_2
    command: mongod --shardsvr --replSet shard2ReplSet --port 27018 --bind_ip_all
    volumes:
      - shard2_2_data:/data/db
    networks:
      - app_network

  shard2_3:
    image: mongo:6.0
    container_name: shard2_3
    command: mongod --shardsvr --replSet shard2ReplSet --port 27018 --bind_ip_all
    volumes:
      - shard2_3_data:/data/db
    networks:
      - app_network

  # Mongos router
  mongos:
    image: mongo:6.0
    container_name: mongos
    depends_on:
      - configsvr1
      - configsvr2
      - configsvr3
      - shard1_1
      - shard1_2
      - shard1_3
      - shard2_1
      - shard2_2
      - shard2_3
    command: >
      mongos --configdb configReplSet/configsvr1:27019,configsvr2:27019,configsvr3:27019 --bind_ip_all --port 27017
    ports:
      - 27017:27017
    networks:
      - app_network

  # Init container to run init.sh
  init-mongo:
    image: mongo:6.0
    container_name: init-mongo
    depends_on:
      - configsvr1
      - configsvr2
      - configsvr3
      - shard1_1
      - shard1_2
      - shard1_3
      - shard2_1
      - shard2_2
      - shard2_3
      - mongos
    volumes:
      - ./:/scripts
    working_dir: /scripts
    entrypoint: ["bash", "/scripts/init.sh"]
    networks:
      - app_network

  # mongodb:
  #   container_name: mongodb
  #   image: mongo:6-jammy
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - dbdata6:/data/db
  #   networks:
  #     - app_network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network
  
  controller:
    container_name: controller
    build:
      context: .
      dockerfile: Dockerfile.controller
    environment:
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      CONTROLLER_PORT: ${CONTROLLER_PORT}
      RABBITMQ_HOSTNAME: ${RABBITMQ_HOSTNAME}
      ELK_HOST: ${ELK_HOST}
      ELK_PORT: ${ELK_PORT}
      REDIS_CONNECTION: redis:6379
    stdin_open: true
    ports:
      - "14620:14620"
      - ${CONTROLLER_PORT}:${CONTROLLER_PORT}
    networks:
      - app_network
  
  ruleengine:
    container_name: ruleengine
    build:
      context: .
      dockerfile: Dockerfile.engine
    environment:
      RABBITMQ_HOSTNAME: ${RABBITMQ_HOSTNAME}
      RABBITMQ_HOSTPORT: ${RABBITMQ_HOSTPORT}
      ELK_HOST: ${ELK_HOST}
      ELK_PORT: ${ELK_PORT}
    stdin_open: true
    ports:
      - "14624:14624"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Default RabbitMQ port
      - "15672:15672" # Management console port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - app_network

  elasticsearch:
    image: elasticsearch:8.16.6
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app_network

  logstash:
    image: logstash:8.16.6
    container_name: log
    ports:
      - "5044:5044"
    environment:
      discovery.seed_hosts: logstash
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - app_network

  kibana:
    image: kibana:8.16.6
    container_name: kib
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - app_network

  k6_lt_peak_load_stress:
    image: grafana/k6:latest
    container_name: k6_lt_peak_load_stress
    volumes:
      - ./k6:/k6
      - ./proto:/k6/proto
      - ./k6/output:/tmp/output
    environment:
      VUS: 3000
      RATE: 1
      DURATION: "1m"
      TEST_NAME: "k6_lt_peak_load_stress"
    depends_on:
      init-mongo:
        condition: service_completed_successfully
    networks:
      - app_network
    entrypoint: ["sh", "-c", "sleep 60 && k6 run /k6/test.js"]

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    networks:
      - app_network

volumes:
  esdata:
    driver: local
  dbdata6:
  configsvr1_data:
  configsvr2_data:
  configsvr3_data:
  shard1_1_data:
  shard1_2_data:
  shard1_3_data:
  shard2_1_data:
  shard2_2_data:
  shard2_3_data:
  redis_data:
  grafana-data:

networks:
  app_network:
    driver: bridge