global: { resolve_timeout: 5m }

route:
  receiver: default

receivers:
  - name: default
    email_configs:
      - to: georgiyshulyak@gmail.com
        from: georgiyshulyak@gmail.com
        smarthost: smtp.example.com:587
        auth_username: georgiyshulyak@gmail.com
        auth_identity: georgiyshulyak@gmail.com
        auth_password: "password"