{
 "title": "prometheus-net",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instances",
    "label": "instances",
    "query": "label_values(http_requests_received_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Realtime memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_working_set_bytes{job!=\"simulator\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "System CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{instance=\"controller:14620\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC collection count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(dotnet_collection_count_total{job=\"controller\"}[$interval])",
     "legendFormat": "Generation-{{generation}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_num_threads{job=\"controller\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"controller\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}