name: Docker Compose CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-stress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Проверка установки
      - name: Start containers and wait for k6
        run: |
          docker-compose up -d
          while [ "$(docker inspect -f '{{.State.Running}}' k6_lt_many_devices_low_rate 2>/dev/null)" = "true" ]; do
            sleep 1
          done
          CONTAINER_EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' k6_lt_many_devices_low_rate 2>/dev/null || echo 1)
          if [ "$CONTAINER_EXIT_CODE" -ne 0 ]; then
            echo "❌ k6 test failed!"
            exit 1
          fi
          docker-compose down
          
      - name: Upload k6 test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: k6-test-results
          path: ./k6-output/
          if-no-files-found: error
