name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-stress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker-compose --version

      - name: Start containers and wait for k6 to finish
        run: |
          docker-compose up -d
          while [ "$(docker inspect -f '{{.State.Running}}' k6_lt_peak_load_stress)" = "true" ]; do
            sleep 1
          done
          CONTAINER_EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' k6_lt_peak_load_stress)
          echo "Container exited with code: $CONTAINER_EXIT_CODE"
          if [ "$CONTAINER_EXIT_CODE" -ne 0 ]; then
            echo "Error: k6 test failed!"
            exit 1
          fi
          docker-compose down
